// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:879326654387:web:f69686df19725cbc8f65c6',
    messagingSenderId: '879326654387',
    projectId: 'ndc95-9af5f',
    authDomain: 'ndc95-9af5f.firebaseapp.com',
    storageBucket: 'ndc95-9af5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFdOfniR7bB5JVWV64F-knfg4rx2i3a6M',
    appId: '1:879326654387:android:7b85575af3068f188f65c6',
    messagingSenderId: '879326654387',
    projectId: 'ndc95-9af5f',
    storageBucket: 'ndc95-9af5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:879326654387:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '879326654387',
    projectId: 'ndc95-9af5f',
    storageBucket: 'ndc95-9af5f.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:879326654387:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '879326654387',
    projectId: 'ndc95-9af5f',
    storageBucket: 'ndc95-9af5f.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:879326654387:web:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '879326654387',
    projectId: 'ndc95-9af5f',
    authDomain: 'ndc95-9af5f.firebaseapp.com',
    storageBucket: 'ndc95-9af5f.firebasestorage.app',
  );
}